name: Weatherbot CI-CD

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: weatherbot
  ACR_NAME: ${{ secrets.ACR_NAME }}
  AKS_CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME }}
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR Login
        run: az acr login --name $ACR_NAME

      - name: Build and Push Image
        run: |
          docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }} .
          docker tag $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }} $ACR_NAME.azurecr.io/$IMAGE_NAME:latest
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:latest

      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}

      - name: Apply/Update CronJob
        run: |
          kubectl apply -f k8s/cronjob.yaml
          kubectl set image cronjob/weatherbot-cronjob \
            weatherbot=$ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}
